# Generated by Django 5.0 on 2025-12-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='gestorCursos.curso'),
            preserve_default=False,
        ),
    ]
